### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by mathigatti** [pyBinSim/pyBinSim#11]
Hi, sorry for the noob question but I'm not sure how to use it. This project looks really amazing but I'm finding it a little bit hard to use. I want to record something, let's say "my_sample.wav" and then being able to move it in space with some command like this.

```python
from pybinsim import move
move("my_sample.wav", position_x, position_y, position_z)
```
This would generate a "moved.wav" file, which is "my_sample.wav" sounding as if it was in the <position_x, position_y, position_z> coordinates.

Is there an easy way to do something like that? I couldn't follow the code, I'm a beginner on audio synthesis.

**Comment by throni3git** [comment]
What you are looking for is binaural synthesis. pyBinSim is a software that convolves an audio signal with prerendered impulse responses (most probably binaural room impulse responses). To "move" a signal in spatial audio is the hard part that has to be done first, pyBinSim just uses the results of that process. I'm not sure the examples in the AppExample repo still work, maybe we should update them.

**Comment by mathigatti** [comment]
Oh I see, thank you very much for the answer!
